### ISSUE TITLE
Is my local setup correct ?

### ISSUE THREAD

**Issue by kissu** [nuxt-community/google-fonts-module#26]
Hi ! 👋🏻

Basically I want to get as much performance as possible, so I've read few articles saying that the best way is still to have Google Fonts locally. So, as far as I understand, the point is to get it at build time and never fetch it ever again (less HTTP requests, etc...).

So, I tried a configuration but I wished to have a confirmation that my setup looks okay
```js
buildModules: [
  [
    '@nuxtjs/google-fonts',
    {
      families: {
        Mali: {
          wght: [400, 600, 700],
        },
      },
      subsets: ['latin'],
      display: 'swap',
      prefetch: false,
      preconnect: false,
      preload: false,
      download: true,
      base64: false,
    },
  ],
],
```

Got the fonts downloaded on build time with `nuxt generate --modern`.
![image](https://user-images.githubusercontent.com/5133074/97246935-e2416280-17fe-11eb-95aa-1e9d3428be73.png)

Then, I added this to my main layout file to have it pretty much everywhere.
```css
html {
  font-family: 'Mali', 'Source Sans Pro', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
    'Helvetica Neue', Arial, sans-serif;
}
```

I checked on Firefox and it seems that I'm downloading it properly from the `/dist` folder !
![image](https://user-images.githubusercontent.com/5133074/97247150-5e3baa80-17ff-11eb-968f-493306bdb33b.png)

Did I miss something or are the options looking good for you ? 😸
